<div class="page-header clearfix">
	<h2 class="pull-left">
		Customers
	</h2>
	<a href="/customers/new" class="btn btn-success pull-right">Create customer</a>

	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Email</th>
				<th>Action</th>
			</tr>
		</thead>
		<?php foreach ($this->customers as $customer): ?>
			<tr>
				<td><?= $customer->getId() ?></td>
				<td><?= $customer->getName() ?></td>
				<td><?= $customer->getEmail() ?></td>
				<td><a href="/customers/edit/<?= $customer->getId() ?>" class="btn btn-primary">Edit</a></td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>

